version: "3.5"

services:
    seq:
        image: datalust/seq:latest
        container_name: seq
        ports:
        - '5341:80'
        environment:
        - ACCEPT_EULA=Y
        networks:
        - gateway-network

networks:
    gateway-network:
        name: gateway-network
